# @package _global_

defaults:
  - /pretraining
  - override /object_class: rack
  - _self_

dataset:
  root: /data/ndf

resources:
  num_workers: 0

training:
  epochs: 2000
  batch_size: 8
  check_val_every_n_epoch: 100
  log_every_n_steps: 10

emb_nn: "dgcnn"
