# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose_all
  - override /task:  reach_target
  - override /phase: all
  - _self_

break_symmetry: False

model:
  break_symmetry: False
  num_points: 256
