# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /task: put_toilet_roll_on_stand
  - override /phase: all
  - _self_

break_symmetry: False

model:
  conditional: True

dm:
  train_dset:
    demo_dset:
      num_points: 256
