# @package _global_

defaults:
  - /train_ndf
  - override /benchmark: ndf
  - _self_

resources:
  num_workers: 16

training:
  check_val_every_n_epoch: 10
  log_every_n_steps: 100
  max_epochs: 375
  batch_size: 3
