# @package _global_

break_symmetry: false
defaults:
- /eval_rlbench.yaml
- override /model: taxpose_all
- override /task: reach_target
- _self_
model:
  break_symmetry: false
  num_points: 256
  z_offset: 0.0
