
# This is the general structure of the datamodule for NDF tasks.
defaults:
  - ../@train_dset.demo_dset.occlusion_cfg: _augmentations
  - ../@val_dset.demo_dset.occlusion_cfg: _augmentations
  - ../@test_dset.demo_dset.occlusion_cfg: _augmentations

train_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${task.name}
    episodes: all
    action_class: ${task.phase.action_class}
    anchor_class: ${task.phase.anchor_class}
    cached: true
    phase: ${task.phase.name}
    teleport_initial_to_final: true
    with_symmetry: True
    occlusion_cfg: ???
    num_points: 256

val_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${task.name}
    episodes: all
    action_class: ${task.phase.action_class}
    anchor_class: ${task.phase.anchor_class}
    cached: true
    phase: ${task.phase.name}
    teleport_initial_to_final: true
    with_symmetry: True
    occlusion_cfg: ???
    num_points: 256

test_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${task.name}
    episodes: all
    action_class: ${task.phase.action_class}
    anchor_class: ${task.phase.anchor_class}
    cached: true
    phase: ${task.phase.name}
    teleport_initial_to_final: true
    with_symmetry: True
    occlusion_cfg: ???
    num_points: 256
