
# This is the general structure of the datamodule for NDF tasks.
defaults:
  - ../@train_dset.demo_dset.occlusion_cfg: _augmentations
  - ../@val_dset.demo_dset.occlusion_cfg: _augmentations

train_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${task.name}
    use_first_as_init_keyframe: False
    episodes: all
    action_class: ${task.phase.action_class}
    anchor_class: ${task.phase.anchor_class}
    cached: true
    phase: ${task.phase.name}
    teleport_initial_to_final: true
    with_symmetry: True
    occlusion_cfg: ???
    num_points: 512
    action_mode: "gripper_and_object"
    anchor_mode: "background_robot_removed"
    include_wrist_cam: True
    gripper_in_first_phase: False

val_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}_val
    task_name: ${task.name}
    use_first_as_init_keyframe: False
    episodes: all
    action_class: ${task.phase.action_class}
    anchor_class: ${task.phase.anchor_class}
    cached: true
    phase: ${task.phase.name}
    teleport_initial_to_final: true
    with_symmetry: True
    occlusion_cfg: ???
    num_points: ${...train_dset.demo_dset.num_points}
    action_mode: ${...train_dset.demo_dset.action_mode}
    anchor_mode: ${...train_dset.demo_dset.anchor_mode}
    include_wrist_cam: ${...train_dset.demo_dset.include_wrist_cam}
    gripper_in_first_phase: ${...train_dset.demo_dset.gripper_in_first_phase}
