# @package _global_

break_symmetry: false
defaults:
- /eval_rlbench.yaml
- override /model: taxpose_all
- override /task: take_money_out_safe
- _self_
dm:
  train_dset:
    demo_dset:
      num_points: 128
model:
  break_symmetry: false
  conditional: true
  num_points: 128
  z_offset: 0.0
