defaults:
  - ndf/_default@_here_
  - _self_

train_folder: bowl_train_new_3_pregrasp
test_folder: bowl_test_new_3_pregrasp

# Dataset Settings
train_dset:
  demo_dset:
    dataset_indices: null
    num_demo: 10

val_dset:
  demo_dset:
    dataset_indices: null
    num_demo: null
