 # @package _global_

defaults:
  - override /task: stack_wine
  - override /phase: place

dm:
  train_dset:
    demo_dset:
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
  val_dset:
    demo_dset:
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
