# @package _global_

defaults:
  - /commands/rlbench/_eval_metrics@_here_
  - override /model: taxpose_tc
  - override /task: take_umbrella_out_of_umbrella_stand
  - override /phase: pregasp
  - _self_
