# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: taxpose_all
  - override /task: phone_on_base
  - override /phase: place
  - _self_

break_symmetry: False

model:
