# @package _global_

defaults:
  - /train_ndf
  - override /benchmark: rlbench
  - _self_

resources:
  num_workers: 16

pretraining:
  mode: none

training:
  max_epochs: 2000
  batch_size: 8
  check_val_every_n_epoch: 10
  log_every_n_steps: 100

dm:
  train_dset:
    num_points: 512
    synthetic_occlusion: False
