# @package _global_

defaults:
  - /eval_rlbench.yaml
  - override /model: taxpose_all
  - override /task: put_knife_on_chopping_board
  - _self_

break_symmetry: False

model:
  # conditional: True
  break_symmetry: False
  num_points: 128

  z_offset: 0.05


dm:
  train_dset:
    demo_dset:
      num_points: 128
