# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: taxpose_all
  - override /task: put_knife_on_chopping_board
  - override /phase: grasp
  - _self_

break_symmetry: False

model:
  # conditional: True
  break_symmetry: False

dm:
  train_dset:
    demo_dset:
      num_points: 128
