name: ???
model_type: residual_flow_diff_emb_transformer

defaults:
  - encoder: dgcnn
  - _self_

pred_weight: True
center_feature: True
inital_sampling_ratio: 1
residual_on: True
cycle: True
freeze_embnn: False
return_attn: True

# We're not using multilateration for the head.
multilaterate: False
mlat_sample: null
mlat_nkps: null

# By default, the number of additional feature channels will be 0.
# But these could be RGB, symmetry features, etc.
feature_channels: 0

# Whether or not we want to include a conditioning vector to include a specific task.
conditional: False

pretraining:
  action:
    ckpt_path: null
  anchor:
    ckpt_path: null
