name: ???
pred_weight: True
emb_nn: "dgcnn"
emb_dims: 512
return_flow_component: False
center_feature: True
inital_sampling_ratio: 1
residual_on: True
num_points: 1024

defaults:
  - optional pretraining_mode: nce_loss
  - encoder: dgcnn
  - _self_

pretraining: null
