name: ???
model_type: residual_flow_diff_emb_transformer

defaults:
  - encoder: dgcnn
  - _self_

pred_weight: True
center_feature: True
inital_sampling_ratio: 1
residual_on: True
cycle: True
freeze_embnn: False
return_attn: True
multilaterate: False
mlat_sample: null
mlat_nkps: null
break_symmetry: True

pretraining:
  action:
    ckpt_path: null
  anchor:
    ckpt_path: null
