defaults:
  - ../_default@_here_
  - _self_

# Dataset Settings
train_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 0
      # - 1
      # - 2
      # - 3
      # - 4
      # - 5
      # - 6
      # - 7

val_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 8
      # - 9
