 # @package _global_

defaults:
  - override /task: put_toilet_roll_on_stand
  - override /phase: place

# Needs override for adding the symmetry features.
model:
  feature_channels: 1

dm:
  train_dset:
    include_symmetry_features: True
    demo_dset:
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
  val_dset:
    demo_dset:
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
