# @package _global_

defaults:
  - /commands/rlbench/_train_taxposed@_here_
  - override /model: taxposed_mlat_s100
  - override /task:  stack_wine
  - override /phase: place
  - _self_

break_symmetry: False
