# @package _global_

defaults:
  - /commands/rlbench/_train_taxposed@_here_
  - override /model: taxposed
  - override /task:  stack_wine
  - override /phase: place
  - _self_

break_symmetry: False

training:
  init_cond_x: True
  freeze_embnn: True
  freeze_residual_flow: True
  freeze_z_embnn: True

  load_from_checkpoint: True
  checkpoint_file: null