# task: bowl_place
name: bowl_place
action_class: 0
anchor_class: 1
action_name: bowl
anchor_name: slab
cloud_type: teleport
softmax_temperature: 1
weight_normalize: l1
checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_bowl_embnn_weights.ckpt
checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_slab_embnn_weights.ckpt
