# task: mug_grasp
name: mug_grasp
action_name: gripper
anchor_name: mug
action_class: 2
anchor_class: 0
cloud_type: pre_grasp
softmax_temperature: 0.1
weight_normalize: softmax
# checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_gripper_embnn_weights.ckpt
# checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
checkpoint_file_action: null
checkpoint_file_anchor: null
