# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: taxpose_all
  - override /task: slide_block_to_target
  - override /phase: preslide
  - _self_

break_symmetry: False

model:
  conditional: True

dm:
  train_dset:
    demo_dset:
      num_points: 256
