job_type: eval_rlbench_${task.name}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _logging
  - _self_

  - optional task: stack_wine #{mug, bottle, bowl}
  - benchmark: rlbench

  # Machinery to load the correct model architecture.
  # The model config can be found in configs/model.
  - model@grasp_model: taxpose
  - model@place_model: taxpose

  # Task-specific settings.
  - task/${benchmark}/${task}/task@task
  - task@grasp_task: ${benchmark}/${task}/phase/grasp
  - task@place_task: ${benchmark}/${task}/phase/place

  # Load the checkpoints appropriately.
  - checkpoints/rlbench@grasp_checkpoints: ${task}/${model@grasp_model}
  - checkpoints/rlbench@place_checkpoints: ${task}/${model@place_model}

policy_spec:
  grasp_model: ${grasp_model}
  place_model: ${place_model}

checkpoints:
  grasp: ${grasp_checkpoints.grasp}
  place: ${place_checkpoints.place}

num_trials: 100
headless: True

resources:
  num_workers: 10

# For prediction.
z_offset: 0.03
