

job_type: eval_metrics_${task.name}_${task.phase.name}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _self_
  - _logging

  - model: taxpose

  - datamodule  # This loops in the dataset.
  - benchmark: rlbench # {ndf, rlbench}
  - optional task: stack_wine
  - optional phase: place
  - task/${benchmark}/${task}/task@task
  - task/${benchmark}/${task}/phase/${phase}@task.phase

checkpoint: ???

seed: 0
inference:
  batch_size: 8
  sigmoid_on: True

split: "train"

resources:
  num_workers: 8

wandb:
  group: Null
