hydra:
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True

experiment: ${model.name}

#### TO BE CHANGED ####
defaults:
  - _self_
  - pose_dist: upright # {upright, arbitrary}
  - object_class: mug #{mug, bottle, bowl}

  # Machinery to load the correct checkpoints.
  - model: release
  - optional checkpoints/ndf@checkpoints.grasp: ${object_class}/${pose_dist}/${model}/grasp
  - optional checkpoints/ndf@checkpoints.place: ${object_class}/${pose_dist}/${model}/place

# checkpoint_file_grasp: ${checkpoints.grasp.ckpt_file}
# checkpoint_file_place: ${checkpoints.place.ckpt_file}
checkpoint_file_grasp: ???
checkpoint_file_place: ???
log_txt_file: ${hydra:runtime.cwd}/test_results.txt # abs path of file to log results

# log saving dir
log_dir: ./results/ndf/${object_class.name}/${pose_dist.name}
num_iterations: 100 # number of trails
data_dir: ./predictions # directory name for data saved
log_every_trial: False # True - log success rate at every trial; False - log only at the end of the # of trials
#### TO BE CHANGED ####

# Model Settings
flow_compute_type: 0
emb_nn: dgcnn
num_points: 1024
emb_dims: ${model.emb_dims}

# Dataset Settings
dataset_index: None
action_class: 0
anchor_class: 1
dataset_size: 300
rotation_variance: 180
translation_variance: 0.5
batch_size: 1
num_workers: 4
cloud_type: init
no_transform_applied: True
point_loss_type: 0
gripper_lr_label: False
return_flow_component: False
center_feature: True
overfit: False
diff_emb: True
diff_transformer: True

#### TO BE CHANGED ####
weight_normalize_place: l1
sigmoid_on: True
rotation_weight: 0
consistency_weight: 1
smoothness_weight: 0.1
pred_weight: ${model.pred_weight}
softmax_temperature: 1
weight_normalize_grasp: softmax
softmax_temperature_grasp: 0.1
residual_on: ${model.residual_on}
#### TO BE CHANGED ####

mlp: False
freeze_embnn: False
return_attn: True
rand_mesh_scale: True
loop: 1
init_distribution_tranform_file: Null

# Loss Settings
lr: 1e-4

# Logging Settings
image_logging_period: 100
debug: False
seed: 10
pybullet_viz: False
only_test_ids: True
exp: debug_eval
num_demo: 12
model_path: multi_category_weights
n_demos: 0
single_instance: False
start_iteration: 0
