job_type: eval_rlbench_${task.name}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _logging
  - _self_

  - benchmark: rlbench
  - optional task: stack_wine

  # Machinery to load the correct model architecture.
  # The model config can be found in configs/model.
  - model: taxpose

  # Task-specific settings.
  - task/${benchmark}/${task}/task@task

policy_spec:
  collision_checking: True
  num_points: 512
  break_symmetry: False
  model: ${model}
  include_rgb_features: False
  add_random_jitter: True
  include_wrist_cam: True
  gripper_in_first_phase: False


# Usually only a single checkpoint, but we could have multiple for each phase.
checkpoints:
  ckpt_file: ???

task:
  action_mode: gripper_and_object
  anchor_mode: background_robot_removed

num_trials: 100
headless: True

resources:
  num_workers: 10

seed: 123456
