

job_type: eval_metrics_${task.name}_${task.phase.name}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _self_
  - _logging

  - model: release

  - datamodule  # This loops in the dataset.
  - benchmark: ndf # {ndf, rlbench}
  - pose_dist: upright # {upright, arbitrary}

  - optional task: stack_wine
  - optional phase: place
  - task/${benchmark}/${task}/task@task
  - task/${benchmark}/${task}/phase/${phase}@task.phase
  - optional checkpoints/rlbench@checkpoints: ${task}/${model}/${phase}

checkpoints:
  ckpt_file: ???

checkpoint: ${checkpoints.ckpt_file}


seed: 0
break_symmetry: True
inference:
  batch_size: 8
  sigmoid_on: True
split: "train"

resources:
  num_workers: 8

wandb:
  group: Null
