hydra:
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True

experiment: residual_flow_test_partial_cloud_initpose

#### TO BE CHANGED ####
defaults:
  - _self_
  - pose_dist: upright # {upright, arbitrary}
  - ablation: 0_no_disp_loss

  # $ablation \in {
  # 0_no_disp_loss,
  # 1_no_corr_loss,
  # 2_no_cons_loss,
  # 3_no_disp_loss_combined,
  # 4_no_residuals,
  # 5_unweighted_svd,
  # 6_no_finetuning,
  # 7_no_pretraining,
  # 8_mlp,
  # 9_low_dim_embedding
  #}
checkpoint_file_grasp: Null # to be filled with trained model
checkpoint_file_place: Null # to be filled with trained model
# checkpoint_file_grasp: ${hydra:runtime.cwd}/trained_models/ndf/mug/${pose_dist.name}/grasp.ckpt
# checkpoint_file_place: ${hydra:runtime.cwd}/trained_models/ndf/mug/${pose_dist.name}/place.ckpt
log_txt_file: ${hydra:runtime.cwd}/test_results_ablation.txt # abs path of file to log results
# log saving dir
log_dir: ./results/ndf/mug_place
num_iterations: 100 # number of trails
object_class: mug
data_dir: mug_place # directory name for data saved
log_every_trial: False # True - log success rate at every trial; False - log only at the end of the # of trials
#### TO BE CHANGED ####

# Model Settings
flow_compute_type: 0
emb_nn: dgcnn
num_points: 1024

# Dataset Settings
dataset_index: None
action_class: 0
anchor_class: 1
dataset_size: 300
action_rotation_variance: 180
translation_variance: 0.5
batch_size: 1
num_workers: 4
cloud_type: init
no_transform_applied: True
point_loss_type: 0
gripper_lr_label: False
return_flow_component: False
center_feature: True
overfit: False
diff_emb: True
diff_transformer: True

#### TO BE CHANGED ####
weight_normalize_place: l1
sigmoid_on: True
rotation_weight: 0
consistency_weight: 1
smoothness_weight: 0.1
softmax_temperature: 1
weight_normalize_grasp: softmax
softmax_temperature_grasp: 0.1
#### TO BE CHANGED ####

return_attn: True
rand_mesh_scale: True
loop: 1
init_distribution_tranform_file: Null

# Loss Settings
lr: 1e-4

# Logging Settings
image_logging_period: 100
debug: False
seed: 10
pybullet_viz: False
only_test_ids: True
demo_exp: grasp_rim_hang_handle_gaussian_precise_w_shelf
exp: debug_eval
num_demo: 12
config: eval_mug_gen
model_path: multi_category_weights
n_demos: 0
single_instance: False
start_iteration: 0
