job_type: eval_rlbench_${task.name}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _logging
  - _self_

  - optional task: stack_wine
  - benchmark: rlbench

  # Machinery to load the correct model architecture.
  # The model config can be found in configs/model.
  - model: taxpose

  # Task-specific settings.
  - task/${benchmark}/${task}/task@task

  # Load the checkpoints appropriately.
  # - checkpoints/rlbench@grasp_checkpoints: ${task}/${model@grasp_model}
  # - checkpoints/rlbench@place_checkpoints: ${task}/${model@place_model}
  - optional checkpoints/rlbench@checkpoints: ${task}/${model}

policy_spec: ${model}

checkpoints:

task:
  action_mode: object
  anchor_mode: single_object

num_trials: 100
headless: True

resources:
  num_workers: 10

# For prediction.
z_offset: 0.03

seed: 123456
