job_type: eval_${task.name}_${pose_dist.name}_${seed}

data_root: ${oc.env:HOME}/datasets

defaults:
  - _logging
  - _self_

    # Machinery to load the correct model architecture.
  # The model config can be found in configs/model.
  - model: ???

  - optional task: mug #{mug, bottle, bowl}
  - pose_dist: upright # {upright, arbitrary}
  - optional benchmark: ndf # {ndf}


  # Task-specific settings.
  - task/ndf/${task}/task@task
  - task/ndf@grasp_task: ${task}/phase/grasp
  - task/ndf@place_task: ${task}/phase/place

  # Load the checkpoints appropriately.
  - checkpoints/ndf@checkpoints: ${task}/${model}
  # - checkpoints/ndf@checkpoints: ${object_class}/${model}


# checkpoint_file_grasp: ${checkpoints.${pose_dist.name}.grasp}
# checkpoint_file_place: ${checkpoints.${pose_dist.name}.place}
# checkpoint_file_place_refinement: ${checkpoints.${pose_dist.name}.place_refinement}
# checkpoint_file_grasp_refinement: ${checkpoints.${pose_dist.name}.grasp_refinement}
checkpoint_file_grasp: null
checkpoint_file_place: null
checkpoint_file_place_refinement: null
checkpoint_file_grasp_refinement: null



# Extra random irrelevant model settings, legacy.
loop: 1
lr: 1e-4

# Legacy NDF model settings.
dgcnn: False
opt_iterations: 250
random: False
acts: all
model_path: multi_category_weights


# Eval Settings
seed: ???  # Seeds we use: 10, 123456, 54321, 123152, 19501
num_points: ${model.num_points}
include_penetration: False
num_samples: 100
model_eval_on: False
num_demo: 12
num_iterations: 100
config: base_cfg
rand_mesh_scale: False
only_test_ids: True
n_demos: 0
single_instance: False
start_iteration: 0

# Logging Settings
# log_dir: logs/ndf_evals
eval_name: ${task.name}_${pose_dist.name}_${model.name}
eval_save_dir: ./  # Dump directly inside the eval directory.
results_file_name: results.txt

pybullet_viz: True
image_logging_period: 100
debug: False

# hydra:
#   run:
#     dir: ${log_dir}/${eval_name}/${now:%Y-%m-%d_%H%M%S}/${seed}
#   sweep:
#     dir: ${log_dir}/${eval_name}/sweep/${now:%Y-%m-%d_%H%M%S}
#     subdir: ${hydra.job.num}
