# Logging Settings
job_name: embedding_pretraining_mug
image_logging_period: 1000

defaults:
  - _self_
  - hydra_logging

seed: 0

training:
  dataset:
    root: ${hydra:runtime.cwd}/data/mug_place/train_data/renders
    pretraining_data_path: ${hydra:runtime.cwd}/third_party/ndf_robot/src/ndf_robot/data
    num_points: 1024
    dataset_index: None
    cloud_class: 0 # 0 for mug, 1 for rack, 2 for gripper
    cloud_type: init
    overfit: false

  loader:
    batch_size: 8
    num_workers: 4





# Network Settings
emb_dims: 512
emb_nn: dgcnn
inital_sampling_ratio: 1
normalize_features: true

# Loss Settings
con_weighting: dist
l2_reg_weight: 0
temperature: 0.1

# Training Settings
checkpoint_file: Null
lr: 1e-4
