# Logging Settings
hydra:
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True

log_dir: logs
experiment: residual_flow_occlusion
image_logging_period: 100

### TO BE CHANGED ###
log_txt_file:  ${hydra:runtime.cwd}/recent_training_paths.txt # absolute path for text file for logging
defaults:
  - _self_
  - object_class: mug # {mug, bottle, bowl}
  - pose_dist: upright # {upright, arbitrary}
  - relationship: place # {place, grasp}
  - model: release
  - task: ${object_class}_${relationship}
  - optional mode: train # $mode \in {train, train_val, validation}
  - checkpoints: ndf/${object_class}/${pose_dist}/${model}/${relationship}

### TO BE CHANGED ###

# Dataset Settings
dataset_root: ${hydra:runtime.cwd}/data
train_data_dir: ${dataset_root}/${task.name}/train_data/renders
test_data_dir: ${dataset_root}/${task.name}/test_data/renders
num_workers: 52
batch_size: 8
num_points: 1024
num_demo: 10
dataset_index: None
object_type: mug
dataset_size: 1000
rotation_variance: 180
translation_variance: 0.5
synthetic_occlusion: True
plane_occlusion: True
plane_standoff: 0.04
ball_occlusion: True
ball_radius: 0.1
gripper_lr_label: False
occlusion_class: 0
overfit: False
seed: 0

# Network Settings
center_feature: True
diff_emb: True
diff_transformer: True
emb_nn: dgcnn
emb_dims: 512
inital_sampling_ratio: 1
flow_compute_type: 0
residual_on: True
pred_weight: True
sigmoid_on: True
return_flow_component: False
mlp: False
multilaterate: True

# Loss Settings
flow_supervision: both
displace_loss_weight: 1
direct_correspondence_loss_weight: 1
consistency_loss_weight: 0.1

# Training Settings
load_from_checkpoint: False
checkpoint_file: ${checkpoints.ckpt_file}
freeze_embnn: False
lr: 1e-4
max_epochs: 1000
