

job_name: residual_flow_occlusion
image_logging_period: 100

log_txt_file:  ${hydra:runtime.cwd}/recent_training_paths.txt # absolute path for text file for logging
defaults:
  - _self_
  - hydra_logging
  - object_class: mug # {mug, bottle, bowl}
  - pose_dist: upright # {upright, arbitrary}
  - relationship: place # {place, grasp}
  - model: release
  - task: ${object_class}_${relationship}
  - optional mode: train # $mode \in {train, train_val, validation}
  # - optional checkpoints/ndf@checkpoints: ${object_class}/${model}
  - checkpoints/pretraining@checkpoints.pretraining
  - optional ablation: 0_no_disp_loss

# Dataset Settings
dataset_root: ${hydra:runtime.cwd}/data
train_data_dir: ${dataset_root}/${task.name}/train_data/renders
test_data_dir: ${dataset_root}/${task.name}/test_data/renders
num_workers: 52
batch_size: 8
num_points: ${model.num_points}
num_demo: 10
dataset_index: None
object_type: mug
dataset_size: 1000
rotation_variance: 180
translation_variance: 0.5
synthetic_occlusion: True
plane_occlusion: True
plane_standoff: 0.04
ball_occlusion: True
ball_radius: 0.1
gripper_lr_label: False
occlusion_class: 0
overfit: False
seed: 0

# Network Settings
center_feature: ${model.center_feature}
diff_emb: True
diff_transformer: True
emb_nn: ${model.emb_nn}
emb_dims: ${ablation.emb_dims}
inital_sampling_ratio: ${model.inital_sampling_ratio}
flow_compute_type: 0
residual_on: ${ablation.residual_on}
pred_weight: ${ablation.pred_weight}
sigmoid_on: True
return_flow_component: ${model.return_flow_component}
mlp: ${ablation.mlp}

pretraining:
  mode: nce_loss
  # checkpoint_file_action: ${checkpoints.pretraining.${model.emb_nn}.${pretraining.mode}.${task.action_name}}
  # checkpoint_file_anchor: ${checkpoints.pretraining.${model.emb_nn}.${pretraining.mode}.${task.anchor_name}}
  checkpoint_file_action: null
  checkpoint_file_anchor: null

# Loss Settings
flow_supervision: both
displace_loss_weight: ${ablation.displace_loss_weight}
direct_correspondence_loss_weight: ${ablation.direct_correspondence_loss_weight}
consistency_loss_weight: ${ablation.consistency_loss_weight}

# Training Settings
load_from_checkpoint: False
# checkpoint_file: ${checkpoints.ckpt_file}
checkpoint_file: null
freeze_embnn: ${ablation.freeze_embnn}
lr: 1e-4
max_epochs: 1000
# checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
# checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_rack_embnn_weights.ckpt
checkpoint_file_action: null
checkpoint_file_anchor: null

ablation_name: ${ablation.name}
