# Logging Settings
hydra:
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True

log_dir: logs
experiment: residual_flow_occlusion
image_logging_period: 100
log_txt_file:  ${hydra:runtime.cwd}/train_ablation.txt
# $task \in {mug_place, mug_grasp}
defaults:
  - _self_
  - task: mug_place
  - ablation: 0_no_disp_loss

  # $ablation \in {
  # 0_no_disp_loss,
  # 1_no_corr_loss,
  # 2_no_cons_loss,
  # 3_no_disp_loss_combined,
  # 4_no_residuals,
  # 5_unweighted_svd,
  # 6_no_finetuning,
  # 7_no_pretraining,
  # 8_mlp,
  # 9_low_dim_embedding
  #}

# Dataset Settings
dataset_root:  ${hydra:runtime.cwd}/data
train_data_dir: ${dataset_root}/${task.name}/train_data/renders
test_data_dir: ${dataset_root}/${task.name}/test_data/renders
num_workers: 52
batch_size: 8
num_points: 1024
num_demo: 10
dataset_index: None
object_type: mug # 
dataset_size: 1000
rotation_variance: 180
translation_variance: 0.5
synthetic_occlusion: True
plane_occlusion: True
plane_standoff: 0.04
ball_occlusion: True
ball_radius: 0.1
gripper_lr_label: False #
occlusion_class: 0
overfit: False
seed: 0

# Network Settings
center_feature: True
emb_nn: dgcnn
sigmoid_on: True
return_flow_component: False

# Loss Settings
flow_supervision: both

# Training Settings
checkpoint_file: Null
checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_rack_embnn_weights.ckpt
lr: 1e-4
max_epochs: 1000
