# Logging Settings
hydra:
  run:
    dir: ${log_dir}/${experiment}/${now:%Y-%m-%d_%H%M%S}
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}

log_dir: logs
experiment: residual_flow_occlusion
image_logging_period: 100
# $task \in {mug_place, mug_grasp}
defaults:
  - task: mug_grasp
 
# Dataset Settings
dataset_root: ./data
train_data_dir: ${dataset_root}/${task.name}/train_data/renders
test_data_dir: ${dataset_root}/${task.name}/test_data/renders
num_workers: 52
batch_size: 8
num_points: 1024
num_demo: 10
dataset_index: None
object_type: mug
dataset_size: 1000
rotation_variance: 180
translation_variance: 0.5
synthetic_occlusion: False
plane_occlusion: True
plane_standoff: 0.04
ball_occlusion: True
ball_radius: 0.1
gripper_lr_label: False
occlusion_class: 0
overfit: False
seed: 0

# Network Settings
center_feature: True
diff_emb: True
diff_transformer: True
emb_nn: dgcnn
emb_dims: 512
inital_sampling_ratio: 1
flow_compute_type: 0
residual_on: True
pred_weight: True
weight_normalize: softmax
sigmoid_on: True
softmax_temperature: 1
return_flow_component: False
mlp: False

# Loss Settings
flow_supervision: action2anchor
point_loss_type: 0
action_weight: 1
rotation_weight: 0
consistency_weight: 1
smoothness_weight: 0.1

# Training Settings
checkpoint_file: Null
checkpoint_dir: ./trained_models
checkpoint_file_action: ${checkpoint_dir}/pretraining_mug_embnn_weights.ckpt
checkpoint_file_anchor: ${checkpoint_dir}/pretraining_rack_embnn_weights.ckpt
freeze_embnn: False
lr: 1e-4
