name: 1_no_corr_loss
displace_loss_weight: 1
direct_correspondence_loss_weight: 0
consistency_loss_weight: 0.1

residual_on: True
pred_weight: True
freeze_embnn: False
checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_rack_embnn_weights.ckpt
mlp: False
emb_dims: 512
