# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose_tc
  - override /task: pick_and_lift
  - override /phase: all
  - _self_


# Training needs to happen for longer with additional context.
training:
  max_epochs: 2000
