# @package _global_

defaults:
  - /commands/ndf/_eval@_here_
  - override /model: taxpose
  - override /task: mug
  - override /pose_dist: arbitrary
  - _self_

break_symmetry: False
model:
  break_symmetry: False
