# @package _global_

defaults:
  - /commands/ndf/_train@_here_
  - _self_

dm:
  train_dset:
    action_rotation_variance: 1e-4
    anchor_rotation_variance: 1e-4
    translation_variance: 1e-4

  val_dset:
    action_rotation_variance: 3.1415
    anchor_rotation_variance: 3.1415
    translation_variance: 0.5
