# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose_tc
  - override /task: pick_up_cup
  - override /phase: all
  - _self_

# Include RGB features in the training dataset + model.
dm:
  train_dset:
    include_rgb_features: True
model:
  feature_channels: 3
