defaults:
  - ndf/_default@_here_
  - _self_

train_folder: bottle_train_new_3_pregrasp
test_folder: bottle_test_new_3_pregrasp

# Dataset Settings
train_dset:
  demo_dset:
    dataset_indices: null
    num_demo: 10

val_dset:
  demo_dset:
    dataset_indices: null
    num_demo: null

test_dset:
  demo_dset:
    dataset_indices: null
    num_demo: null
