# A github action that builds a container image for the project.

name: Build Container

on:
  push:
    branches:
      - main

    paths:
      # This is the entire list of files that will trigger the workflow.
      - Dockerfile
      - pyproject.toml
      - requirements-gpu.txt
      - .github/workflows/build-container.yaml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: beisner/taxpose:latest
