name: Build Site

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.9'
      ##############################################

      - name: Install specific pip.
        run: pip install pip==23.0.0

      - name: Install doc requirements.
        run: pip install mkdocs-material mkdocstrings[python]

      - name: Build mkdocs site
        working-directory: docs
        run: mkdocs build

      - name: Upload the built site.
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: site
          path: docs/site/
