name: Build Site

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.9'
      ##############################################

      - name: Install CPU version of torch.
        run: pip install torch==1.11.0+cpu torchvision==0.12.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Install the torch-geometric.
        run: pip install pyg_lib==0.1.0 torch_scatter==2.0.9 torch_sparse==0.6.15 torch_cluster==1.6.0 torch_spline_conv==1.2.1 -f https://data.pyg.org/whl/torch-1.11.0+cpu.html

      - name: Install pytorch3d dependencies.
        run: pip install fvcore iopath

      - name: Install pytorch3d
        run: pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html

      - name: Install Dependencies
        run: pip install -e ".[build_docs]"

      - name: Install ndf_robot
        run: pip install -e third_party/ndf_robot

      - name: Build mkdocs site
        working-directory: docs
        run: mkdocs build

      - name: Upload the built site.
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: site
          path: docs/site/
