name: Compute the docker tag for this branch

on:
  workflow_call:
    outputs:
      image_tag:
        description: 'The tag to use for the docker image'
        value: ${{ jobs.compute_tag.outputs.image_tag }}

jobs:
  compute_tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - id: set_tag
        run: |
          branch_name="${{ github.head_ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            sanitized_branch_name="${branch_name//\//-}"
            echo "tag=${sanitized_branch_name}" >> $GITHUB_OUTPUT
          else
            sanitized_branch_name="${GITHUB_REF#refs/heads/}"
            sanitized_branch_name="${sanitized_branch_name//\//-}"
            echo "tag=${sanitized_branch_name}" >> $GITHUB_OUTPUT
          fi
