name: Merge Checks

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compute_tag:
    uses: ./.github/workflows/compute-tag.yaml

  echo_tag:
    runs-on: ubuntu-latest
    needs: compute_tag
    steps:
      - run: echo ${{ needs.compute_tag.outputs.image_tag }}

  test:
    uses: ./.github/workflows/run-tests.yaml
    needs: compute_tag
    with:
      install_string: .[develop]
      # Get the image tag from the compute_tag job.
      image_tag: ${{ needs.compute_tag.outputs.image_tag }}

  build_site:
    uses: ./.github/workflows/build-site.yaml
