name: Merge Checks

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compute_tag:
    uses: ./.github/workflows/compute-tag.yaml

  test:
    uses: ./.github/workflows/run-tests.yaml
    with:
      install_string: .[develop]
      image_tag: ${{ needs.compute_tag.outputs.image_tag }}

    needs: compute_tag

  build_site:
    uses: ./.github/workflows/build-site.yaml
