name: Run Tests

on:

  workflow_call:
    inputs:
      install_string:
        required: True
        type: string
      image_tag:
        required: True
        type: string
        default: "latest"

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      # Image tag is "latest" if the branch is main, else it is the branch name.
      image: beisner/taxpose:${{ inputs.image_tag }}

    defaults:
      run:
        working-directory: /opt/baeisner/code

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Code Quality
        run: python -m black taxpose/ tests/ --check

      - name: MyPy Typechecking
        run: python -m mypy taxpose/ tests/

      # Run tests.
      - name: Test with pytest
        run: python -m pytest tests/
